apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${NAME}
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${NAME}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ${NAME}
    spec:
      containers:
        - name: php
          image: ${IMAGE}
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: ${NAME}-env
          volumeMounts:
            - name: storage
              mountPath: /var/www/html/storage
            - name: code
              mountPath: /code
        - name: nginx
          image: nginx:stable-alpine
          imagePullPolicy: Always
          volumeMounts:
            - name: code
              mountPath: /var/www/html
            - name: config
              mountPath: /etc/nginx/conf.d
            - name: storage
              mountPath: /var/www/html/storage
      restartPolicy: Always
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: ${NAME}-storage
        - name: code
          persistentVolumeClaim:
            claimName: ${NAME}-code
        - name: config
          configMap:
            name: ${NAME}-config
            items:
              - key: default.conf
                path: default.conf
