apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: ${NAME}
resources:
- namespace.yaml
- pvc.yaml
- secret.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
