apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${NAME}-storage
  namespace: apps
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${NAME}-code
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
