apiVersion: v1
kind: Secret
metadata:
  name: ${NAME}-env
  namespace: apps
type: Opaque
stringData:
  APP_DEBUG: 'false'
  APP_ENV: production
  APP_KEY: ${APP_KEY}
  APP_NAME: ${NAME}
  APP_URL: https://${SUBDOMAIN}budget-tracker.home
  BROADCAST_DRIVER: log
  CACHE_DRIVER: file
  DB_CONNECTION: sqlite
  DB_HOST: ${DB_HOST}
  DB_DATABASE: ${DB_NAME}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_PORT: '3306'
  DB_USERNAME: ${DB_NAME}
  IGNITION_ENABLE_RUNNABLE_SOLUTIONS: 'false'
  LOG_CHANNEL: stack
  LOG_LEVEL: debug
  MAIL_ENCRYPTION: null
  MAIL_FROM_ADDRESS: 'hello@example.com'
  MAIL_FROM_NAME: 'Budget Tracker'
  MAIL_HOST: mailpit
  MAIL_MAILER: smtp
  MAIL_PASSWORD: null
  MAIL_PORT: '1025'
  MAIL_USERNAME: null
  QUEUE_CONNECTION: sync
  SESSION_DRIVER: file
  SESSION_LIFETIME: '1440'
  TELESCOPE_ENABLED: 'true'
