apiVersion: v1
kind: Service
metadata:
  name: ${NAME}
  namespace: apps
spec:
  ports:
  - name: fastcgi
    port: 80
    protocol: TCP
    targetPort: 9000
  selector:
    app: ${NAME}
  type: ClusterIP
