name: deploy
on:
  workflow_dispatch:
  workflow_run:
    workflows: [test]
    types: [completed]

env:
  DOCKER_REGISTRY_URL: harbor-core.registry.svc:80

jobs:
  deploy:
    name: Build and deploy application
    runs-on: arc-runner-set
    environment: production
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    concurrency:
      group: production
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - name: Extract branch name
        id: branch
        run: |
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo $GIT_BRANCH

          if [[ $GIT_BRANCH == feature/* ]]; then
            BRANCH="${GIT_BRANCH##*/}"
          elif [[ $GIT_BRANCH == main ]] || [[ $GIT_BRANCH == dev ]] || [[ $GIT_BRANCH == stage ]]; then
            BRANCH="$GIT_BRANCH"
          else
            BRANCH=""
          fi

          echo "name=$BRANCH" >> $GITHUB_OUTPUT
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.DOCKER_REGISTRY_URL }}/default/budget-tracker
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,value=latest
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
          buildkitd-config-inline: |
            [registry."${{ env.DOCKER_REGISTRY_URL }}"]
              insecure = true
              http = true
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/prod/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.DOCKER_REGISTRY_URL }}/default/budget-tracker:latest
          cache-to: type=inline
      - name: Prepare k8s manifests
        run: |
          NAME="budget-tracker-${{ steps.branch.outputs.name }}"
          find k8s -type f | xargs sed -i -e "s/\${NAME}/$NAME/g"

          if [[ ${{ steps.branch.outputs.name }} == main ]]; then
            SUBDOMAIN=""
          else
            SUBDOMAIN="${{ steps.branch.outputs.name }}."
          fi
          find k8s -type f | xargs sed -i -e "s/\${SUBDOMAIN}/$SUBDOMAIN/g"

          APP_KEY="base64:$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1 | base64)"
          find k8s -type f | xargs sed -i -e "s/\${APP_KEY}/$APP_KEY/g"

          IMAGE="${{ fromJSON(steps.meta.outputs.json).tags[1] }}"
          find k8s -type f | xargs sed -i -e "s/\${IMAGE}/$IMAGE/g"
      - name: Update k8s resources
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          ./kubectl apply -k k8s --dry-run=client -o yaml
#      - uses: ravsamhq/notify-slack-action@v2
#        if: always()
#        with:
#          status: ${{ job.status }}
#          notification_title: "Workflow {workflow} {status_message}"
#          footer: ""
#          notify_when: "failure"
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
