name: deploy
on:
  workflow_dispatch:
  workflow_run:
    workflows: [test]
    types: [completed]
jobs:
  dockerhub:
    name: Deploy to Docker Hub
    runs-on: arc-runner-set
    #runs-on: ubuntu-20.04
    environment: development
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    concurrency:
      group: development
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - name: Set credentials
        run: |
          mkdir ~/.docker
          echo "{\"auths\": {\"harbor-registry.registry.svc:5000\": {\"auth\": \"${{DOCKER_AUTH_TOKEN}}\"}}}" > ~/.docker/config.json
          cat  ~/.docker/config.json
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
          config-inline: |
            [registry."harbor-registry.registry.svc:5000"]
              insecure = true
              http = true
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/dev/Dockerfile
          push: true
          tags: harbor-registry.registry.svc:5000/library/budget-tracker:latest
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
#      - uses: ravsamhq/notify-slack-action@v2
#        if: always()
#        with:
#          status: ${{ job.status }}
#          notification_title: "Workflow {workflow} {status_message}"
#          footer: ""
#          notify_when: "failure"
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Inspect
        run: |
          docker buildx imagetools inspect harbor-registry.registry.svc:5000/library/budget-tracker:latest
#  flyio:
#    name: Deploy to Fly.io
#    runs-on: ubuntu-20.04
#    environment: production
#    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
#    concurrency:
#      group: production
#      cancel-in-progress: true
#    env:
#      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
#    steps:
#      - uses: actions/checkout@v3
#      - uses: superfly/flyctl-actions/setup-flyctl@master
#      - run: flyctl deploy
#      - name: Create Sentry release
#        uses: getsentry/action-release@v1
#        env:
#          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
#          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
#          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
#        with:
#          environment: production
#      - uses: ravsamhq/notify-slack-action@v2
#        if: always()
#        with:
#          status: ${{ job.status }}
#          notification_title: "Workflow {workflow} {status_message}"
#          footer: ""
#          notify_when: "failure"
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

